#!/bin/bash

eval `gnome-keyring-daemon --start`

xrdb -merge .Xresources
xmodmap .xmodmap-cuttlefish

trayer --edge top --align right --SetDockType true \
    --expand false --width 10 --transparent true --tint 0x191970 --height 12 &

feh --bg-center Pictures/wallpaper/japonica-wallpaper.jpg
#xsetroot -solid midnightblue

xfce4-power-manager &
xscreensaver -no-splash &
xcompmgr &

tomboy &
gstm &
synaptics-setup.sh &

if [ -x /usr/bin/nm-applet ] ; then
    nm-applet --sm-disable &
fi

if [ -x /usr/bin/xfce4-power-manager ] ; then
    (sleep 3 ; xfce4-power-manager) &
fi

exec xmonad
